name: toonder_comic
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  hexcolor: ^3.0.1
  http: ^0.13.5
  page_indicator: ^0.4.1
  progressive_image: ^2.0.1
  smooth_page_indicator: ^1.0.1
  carousel_slider: ^4.2.1
  flutter_bloc: 8.1.2
  equatable: 2.0.5
  dio: 5.1.1
  shimmer: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
